
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfbioedkpewrmnozhicd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mYmlvZWRrcGV3cm1ub3poaWNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MDIzMzksImV4cCI6MjA1Nzk3ODMzOX0.jFODx2FXmWdMETgqU0RWOSK1NZ1OJYGPjpSrxwli5bw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'x-client-info': `lovable-app`
    }
  }
});
